Repository skynexui/components, pull requests merged in 2021-09, with the labels that each got.

#18 docs: add MIT license
  LICENSE
Labels: 📖 documentation

#20 Creating project folder and moving docs folder to inside it
  projects/docs-web/.gitignore
  projects/docs-web/next.config.js
  projects/docs-web/package.json
  projects/docs-web/pages/_app.js
  projects/docs-web/pages/index.md
  projects/docs-web/theme.config.js
  projects/docs-web/yarn.lock
Labels: ✅ needs approval

#24 docs: fix broken downloads removing .npmrcs
  examples/with-expo/.npmrc
  examples/with-monorepo-nextjs-expo/.npmrc
  examples/with-nextjs/.npmrc
Labels: ✅ needs approval

#25 ci: add support to Conventional Commits automatically with Commitzen
  .husky/pre-commit
  package.json
  yarn.lock
Labels: ✅ needs approval

#27 fix: broken examples by UIProvider not being exported correctly
  examples/with-expo/README.md
  examples/with-expo/yarn.lock
  examples/with-monorepo-nextjs-expo/README.md
  src/theme/provider/UIThemeProvider/native/index.tsx
  src/theme/provider/UIThemeProvider/web/index.tsx
Labels: 🐞 bug

#28 ci: add the contribution flow for make extensions easier
  .gitignore
  README.md
  package.json
  yarn.lock
Labels: ⚠️ WIP
